### ISSUE TITLE
How do we login to Overleaf? 

### ISSUE THREAD

**Issue by ericgaspar** [YunoHost-Apps/overleaf_ynh#4]
After first install, I am unable to login to the app...

**Comment by h3ndrik** [comment]
well for me the email of the admin-user (provided during install) worked. nothing else

in the `/var/log/overleaf/web.log` there is an error message, maybe related to the login not working:

```
Found user: hendrik@[...],root@[...],admin@[...],webmaster@[...],abuse@[...],[...] Name: Hendrik L[...] DN: uid=hendrik,ou=users,dc=yunohost,dc=org                                                                                                             
events.js:377
      throw er; // Unhandled 'error' event
      ^                                                                                                                                                              
TypeError: email.trim is not a function                                                                                             
    at Object.parseEmail (/var/www/overleaf/live/services/web/app/src/Features/Helpers/EmailHelper.js:17:17)
    at Object.validateEmail (/var/www/overleaf/live/services/web/app/src/Features/Authentication/AuthenticationManager.js:116:32)
    at Object._registrationRequestIsValid (/var/www/overleaf/live/services/web/app/src/Features/User/UserRegistrationHandler.js:16:4
8)
    at Object.registerNewUser (/var/www/overleaf/live/services/web/app/src/Features/User/UserRegistrationHandler.js:45:33)
    at createIfNotExistAndLogin (/var/www/overleaf/live/services/web/app/src/Features/Authentication/AuthenticationManager.js:63:19)
    at /var/www/overleaf/live/services/web/app/src/Features/Authentication/AuthenticationManager.js:377:9
    at /var/www/overleaf/live/node_modules/mongoose/lib/model.js:5074:18
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
[...]
```

**Comment by rmueck** [comment]
> After first install, I am unable to login to the app...

Same issue here!

**Comment by rmueck** [comment]
I was able to create the initial admin user by visiting:

https://overleaf.mydomain.org/launchpad

**Comment by ericgaspar** [comment]
@rmueck Yes, thanks, tested and working!
